import time 
import turtle 
screen = turtle.Screen()
screen.setup(380, 110, startx=-1, starty=-20)
t = turtle.Turtle()
time = (time.strftime("%I:%M:%S %p"))
t.penup()
t.goto(0,-30)
t.pendown()
t.write(time,align="center",font=("arial",40,"bold"))
t.pensize(5)
t.forward(160)
t.left(90)
t.forward(60)
t.left(90)
t.forward(320)
t.left(90)
t.forward(60)
t.left(90)
t.forward(160)
t.hideturtle()
turtle.done()